### ISSUE TITLE
The toolkit could use more complete documentation on usage

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model-toolkit#10]
The basic "getting started" documentation is fine in the main README, but the site lacks more specific documentation about the library of method in the toolkit. Perhaps a "readTheDocs" generated directly from the embedded code directives or other templates(?) and kept current by some kind of utility script, would fix this.

**Comment by sierra-moxon** [comment]
Hi @RichardBruskiewich  :) - I added two jupyter notebooks to this repository during the last release, and the README Deepak has does have some good examples of usage.  Shall we close this ticket?

**Comment by RichardBruskiewich** [comment]
Sorry for the slow reply @sierra-moxon ... I totally trust that  you did the needful here!
