### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by andrewsu** [biolink/biolink-model-toolkit#110]
This is my "hello world" attempt at using BMT, and I'm getting this error `HTTPError: HTTP Error 404: https://raw.githubusercontent.com/usr/local/lib/python3.8/dist-packages/linkml_runtime/linkml_model/model/schema/types.yaml`

https://colab.research.google.com/drive/1m4ZHAV8Nbi_vCXQaMvEjftUbq0wxlEzt?usp=sharing

I get something similar when I try it locally instead of colab.  It looks like it's trying to mix a remote URL with a local path?

![image](https://user-images.githubusercontent.com/2635409/222344687-f4d7461d-315e-4f47-9287-0e3bf6f9efb5.png)

**Comment by sierra-moxon** [comment]
Thanks @andrewsu  - https://github.com/linkml/linkml-runtime/pull/253

**Comment by sierra-moxon** [comment]
Note: new release: https://github.com/linkml/linkml-runtime/releases/tag/v1.4.8  
I believe recreating your virtual environment will pull in the new release and get you going again.

**Comment by andrewsu** [comment]
confirmed, thanks for the quick fix!
