### ISSUE TITLE
Latest Linkml on fresh install of bmt errors out. 

### ISSUE THREAD

**Issue by YaphetKG** [biolink/biolink-model-toolkit#155]
When doing a fresh install of bmt, it pulls in latest Linkml (v1.6.1) and that generates the following error when creating a new toolkit object :
```
...
    self.exact_mappings = [v if isinstance(v, URIorCURIE) else URIorCURIE(v) for v in self.exact_mappings]
  File "/home/airflow/.local/lib/python3.10/site-packages/linkml_runtime/utils/metamodelcore.py", line 104, in __init__
    raise ValueError(f"{v} is not a valid URI or CURIE")
ValueError: WIKIDATA_PROPERTY:P854 is not a valid URI or CURIE
```

**Comment by sierra-moxon** [comment]
thanks for the heads up @YaphetKG. :)  I am also getting that error on a branch of Biolink that uses the most up-to-date packages.  I just went to check the specs on this repo (I thought maybe we were being too permissive) but I noticed in pyproject.toml, and poetry.lock we limit linkml-runtime to >=1.5.1 and <=1.6.0

when I do a fresh install of my environment, I get linkml-runtime 1.5.3 and am able to create a new toolkit object.  I also tried pulling bmt into a new repo that I just created, and I get linkml-runtime 1.5.5.  

How do you pull in bmt?

**Comment by sierra-moxon** [comment]
working on a [fix upstream](https://github.com/linkml/linkml-runtime/pull/283), but for now, I would try to follow the poetry specs here, and keep linkml-runtime below 1.6.0 in your implementation.

**Comment by YaphetKG** [comment]
Thanks Sierra, yeah I pinned link to 1.6.0 and it worked for me
