### ISSUE TITLE
element not json serializable

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model-toolkit#21]
a call to get_element produces something that can be cast to a dictionary.  For most entities, this can be directly converted into json.

However, there are a number of entities for which this does not work.  `negatively regulates, entity to entity` is one.

It's due to the local_names key which has as its value a list of LocalName objects, which won't serialize.

**Comment by cbizon** [comment]
SlotDefinition in slot_usage is another culprit

**Comment by deepakunni3** [comment]
I think the safe way to handle this would be to ensure that bmt always returns JSON instead of instances of ClassDefinition or SlotDefinition.

I can have this be part of the next minor release: `0.4.0`

**Comment by deepakunni3** [comment]
@cbizon After investigating further into this issue - how are you converting the objects to a dictionary?

Is it the default `obj.__dict__` method?

**Comment by sierra-moxon** [comment]
Per Deepak's comments on https://github.com/TranslatorSRI/bl_lookup/issues/15 <-- I'm closing this?  Please feel free to reopen if its still not work or can't be execute the way Deepak shows?
