### ISSUE TITLE
Toolkit import error using 0.6.0 distro for BMT

### ISSUE THREAD

**Issue by GregHydeDartmouth** [biolink/biolink-model-toolkit#41]
I'm having trouble importing the Toolkit from bmt on a fresh python environment using Python 3.8.8.

I installed with: pip install bmt

Then when I try: from bmt import Toolkit 
I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ghyde/test1/testbmt/bmt_test/lib/python3.8/site-packages/bmt/__init__.py", line 1, in <module>
    from bmt.toolkit import Toolkit
  File "/home/ghyde/test1/testbmt/bmt_test/lib/python3.8/site-packages/bmt/toolkit.py", line 4, in <module>
    from linkml_model.meta import SchemaDefinition, Element, Definition, ClassDefinition, SlotDefinition
ModuleNotFoundError: No module named 'linkml_model'

**Comment by sierra-moxon** [comment]
Thanks @GregHydeDartmouth - we had a change to the underlying linkml import - fixing! :)

**Comment by sierra-moxon** [comment]
@GregHydeDartmouth - can you please try again? - new release of BMT (0.7.0) includes a linkml upgrade.

**Comment by GregHydeDartmouth** [comment]
@sierra-moxon Seems to be working just fine. Thanks!!
