### ISSUE TITLE
Documentation  The technical documentation for BMT can be found at bmt.readthedocs.io

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model-toolkit#47]
broken link

**Comment by jorgeqscholz** [comment]
Please, there is not much documentation elsewhere.

**Comment by nlharris** [comment]
@RichardBruskiewich do you know how to fix this?

**Comment by RichardBruskiewich** [comment]
Hi @nlharris, in fact, @sierra-moxon is maintaining BMT.  I think I may have mentioned the broken link to her but just in case, maybe assign the issue to her.  I know that she has some good sample code somewhere.

At any rate, she'll likely know how to quickly fix the docs generation.

**Comment by cmungall** [comment]
I can have @hrshdgd do this when he is back from vacation - but this should be straightforward publishing on rtd

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model-toolkit/ is up.  Happy for feedback. :)
