### ISSUE TITLE
Verbiage when initializing bmt

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model-toolkit#5]
When initializing bmt with `biolink-model.yaml`, I get the following printed onto the console:

```
Warning: class "drug exposure" slot "drug" does not reference an existing slot.  New slot was created.
Warning: class "treatment" slot "has exposure parts" does not reference an existing slot.  New slot was created.
Warning: class "pairwise interaction association" slot "interacting molecules category" does not reference an existing slot.  New slot was created.
Unrecognized prefix: SEMMEDDB
Unrecognized prefix: WD
Unrecognized prefix: dct
Unrecognized prefix: oban
Unrecognized prefix: HANCESTRO
Unrecognized prefix: RNAcentral
Unrecognized prefix: IntAct
Unrecognized prefix: Reactome
Unrecognized prefix: VMC
Unrecognized prefix: CIViC
Unrecognized prefix: ECTO

```

Is there a way to suppress these messages? Are these messages being sent to console via logging or via print statements? 

@hsolbrig Thoughts?

**Comment by hsolbrig** [comment]
The glib answer would be to fix the biolink-model itself -- get those prefixes defined and address the other problems.  If this is not workable, however, we could add an "ignore warnings" flag to the generator.

**Comment by deepakunni3** [comment]
Yes, I would agree that we fix the model.
In the interim, a `ignore_warnings` parameter would be very useful.
OR
Since bmt is being used at many locations in KGX, the verbiage could be controlled. For example, if the errors are bring thrown at `logging.warning` level then we could suppress them at runtime by any tool thats using bmt as a dependency.
