### ISSUE TITLE
Optionally provide aliases with get_descendants(), etc.

### ISSUE THREAD

**Issue by patrickkwang** [biolink/biolink-model-toolkit#54]
This is motivated by the desire to receive `biolink:ChemicalSubstance` as a descendant of `biolink:NamedThing`, for backwards compatibility.

**Comment by cmungall** [comment]
I'm tending against this. I think we should make it very easy for people to compose two calls together, e.g.

 * lookup by alias `o` descendants

The caller can then implement any logic they need for edge cases, e.g

 - aliases are not guaranteed unique
 - allowing for case insensitive matches, camelcase transforms or even levenstein distance
 - specifying alternate concept IDs in queries

I think the core lib could become bloated if we try and anticipate every possible use case and way functions can be combined

This would be great for a UI though

I could be persuaded to have something like this in a kind of supplemental grab-bag utility library that wraps a simpler core lib

I may be being a too pedantic computer scientist though so if there is strong need for this we can add (I am guessing not though given I assume this was August!)
