### ISSUE TITLE
Cannot import bmt in python: TypeError: dataclasses_init_fn_with_kwargs() missing 1 required positional argument: 'globals'

### ISSUE THREAD

**Issue by ehinderer** [biolink/biolink-model-toolkit#59]
I installed via pip on my Windows machine and any time I try to import the module, I get the error above.

**Comment by RichardBruskiewich** [comment]
Had this error before on MacOSX See https://github.com/linkml/linkml/issues/737.

However, the Biolink 2.4.8 to 3.0.0 divide may be causing some issues now as well:  Sierra and I worked through some odd dependencies issues there, the other day relating to LinkML. 

Maybe try updating your BMT version but also, alongside, pin your local requirements to

If using Biolink Model 2.4.8 or older, use BMT `bmt==0.8.4`
For Biolink 3.0, us `bmt>=0.8.9` (actually, latest is 0.8.10 but that newer release just has some new methods which are unlikely used by too many folks)

You might also wish to pin your LinkML to the following (however, @sierra-moxon can comment on that one...)
```
linkml-runtime>=1.3.1
linkml>= 1.3.2
```

I hope this helps

**Comment by sierra-moxon** [comment]
closing for now as a workaround is above; please of course reopen if this is still an issue. :)
