### ISSUE TITLE
add biolink 2.2 changes to BMT

### ISSUE THREAD

**Issue by GregHydeDartmouth** [biolink/biolink-model-toolkit#60]
Just adding a reminder issue to include the newest biolink changes into BMT. In particular I'm hoping to have the edge biolink:has_real_world_evidence_of_association_with included into the model for easier parsing of trapi messages that include that edge.

**Comment by sierra-moxon** [comment]
@GregHydeDartmouth - note 0.7.4 released today with biolink-model 2.2.3 support.

**Comment by sierra-moxon** [comment]
please reopen if I can help further.
