### ISSUE TITLE
names() does not work as expected

### ISSUE THREAD

**Issue by patrickkwang** [biolink/biolink-model-toolkit#7]
I expected this to return a list of all valid arguments to get_element().

It seems to be missing many, and has some duplicates.

I generated the toolkit using
```
Toolkit('https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.yaml')
```

**Comment by deepakunni3** [comment]
This is fixed as of `0.3.0` release.

The `names()` method has been deprecated in favor of `get_all_elements()` which returns all classes, slots, and types.
