### ISSUE TITLE
Given a URI, can on get the CURIE (or vice versa?)

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model-toolkit#76]
I don't know if this is a general LinkML use case or just a Biolink Model `prefixes` processing use case, but what is the best way to map a URI onto it's CURIE (or _vice versa_?)

**Comment by sierra-moxon** [comment]
```
bmt.toolkit_generator.namespaces.uri_for(identifier)
bmt.toolkit_generator.namespaces.prefix_for
```
