### ISSUE TITLE
class/slot string formatting

### ISSUE THREAD

**Issue by patrickkwang** [biolink/biolink-model-toolkit#9]
Currently `Toolkit.get_element()`, `.ancestors()`, etc. takes spaced strings e.g. "related to" or "phenotypic feature", in contrast with snake case "related_to" or Pascal case "PhenotypicFeature". It would be convenient for my use case if the format were consistent with that used by the [Reasoner API](https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI).

In theory this library could support all three formats at the same time.

**Comment by deepakunni3** [comment]
This is now fixed as of `0.3.0` release.
