### ISSUE TITLE
Cannot find documentation any more

### ISSUE THREAD

**Issue by slobentanzer** [biolink/biolink-model-toolkit#90]
The link you gave in #66 is not functional any more.

Thanks!

**Comment by sierra-moxon** [comment]
Hi @slobentanzer - apologies it took a bit for us to get this working again, it should be up again.

**Comment by sierra-moxon** [comment]
doc is better but not complete.

**Comment by sierra-moxon** [comment]
ok, now I see it fully available! phew :)
