### ISSUE TITLE
initialization time is too slow

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model-toolkit#91]
We've had two reports that BMT initialization is slow.  One user reports that it is intermittent, and the other finds it fairly frequently to be too slow on initialization.  

One possibility is that resolving the LinkML:types import is intermittently slow, but we need to investigate.

**Comment by cmungall** [comment]
https://github.com/linkml/linkml/issues/1012

**Comment by sierra-moxon** [comment]
I refactored the toolkit method to depend on linkml SchemaView instead of generating a schema-view like object itself.  This removes the direct linkml dependency from BMT.  We now depend only on linkml-runtime.  Next step is to test what initialization looks like with this refactoring.

**Comment by sierra-moxon** [comment]
I'm going to close this as fixed, please reopen if it still seems too slow to initialize
