### ISSUE TITLE
bmt version 0.9.0 causing compatibility issues with reasoner-validator

### ISSUE THREAD

**Issue by CaseyTa** [biolink/biolink-model-toolkit#97]
Seems that bmt version 0.9.0 is having compatibility issues with reasoner-validator? 

Our continuous monitoring tests for COHD are failing this weekend after the release of bmt 0.9.0. It seems like our [github workflow](https://github.com/WengLab-InformaticsResearch/cohd_api/blob/master/.github/workflows/cohd-monitor.yml) ends up installing reasoner-validator 2.0.0. Output messages when trying to install bmt and reasoner-validator include:

```
INFO: pip is looking at multiple versions of bmt to determine which version is compatible with other requirements. This could take a while.
...
INFO: pip is looking at multiple versions of reasoner-validator to determine which version is compatible with other requirements. This could take a while.
```

Instructing the workflow to install bmt version 0.8.12 specifically fixes the issue (reasoner-validator 3.1.4 gets installed)

**Comment by sierra-moxon** [comment]
I think you've moved past this version of BMT, @CaseyTa, is that right?

**Comment by CaseyTa** [comment]
@sierra-moxon yes, thanks!
